liber: Add missing perf entries in framework compatibility matrix
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:                                      vendor.qti.memory.pasrmanager@1.1::IPasrManager/pasrhal                                                         vendor.qti.qspmhal@1.0::IQspmhal/default            Suggested fix:                                          1. Update deprecated HALs to the latest version.        2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 4.            3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 4 where applicable.4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success

Change-Id: Ie9cb6e68c13465c7983e8fd0d915eeb5c3e86c40